// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhwblzpcdpyvahhyogag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1od2JsenBjZHB5dmFoaHlvZ2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTY0NTcsImV4cCI6MjA2MDA5MjQ1N30.MT1K_Xcns4KOwKvp4FdbXsmItBJnugvjyYhZXqG-UUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);